### ISSUE TITLE
Will you provide the pretrained model?

### ISSUE THREAD

**Issue by GuideWsp** [xiezw5/Component-Divide-and-Conquer-for-Real-World-Image-Super-Resolution#1]

**Comment by xiezw5** [comment]
Yes, it will be released soon.

**Comment by aligoglos** [comment]
Please upload on drive.

**Comment by ABDOELSHEMY** [comment]
please upload the Pretrained models on drive or something easy to download from, thank you

**Comment by zhihongp** [comment]
Ran into problems with pre-trained models when run `./test_models_pc.sh cdc_x2_test ./CDC_test.py ./models/HGSR-MHR_X2_CDC.pth 2`

Could you help double check?  BTW, the `x4` version seems to work, and `x3` has `load_state_dict` issue too.

> Initializing DataSet, image list: ./DRealSR/Test_x2 ...
Found 83 HR 83 LR ...
Build Generator Net...
Loading from DataParallel module......
Traceback (most recent call last):
  File "../TorchTools/TorchNet/tools.py", line 178, in load_weights
    model.load_state_dict(model_weights, strict=strict)
  File "./lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for HourGlassNetMultiScaleInt:
	Missing key(s) in state_dict: "flat_map.2.1.weight", "flat_map.2.1.bias", "flat_map.4.0.weight", "flat_map.4.0.bias", "edge_map.2.1.weight", "edge_map.2.1.bias", "edge_map.4.0.weight", "edge_map.4.0.bias", "corner_map.2.1.weight", "corner_map.2.1.bias", "corner_map.4.0.weight", "corner_map.4.0.bias", "upsample_flat.2.1.weight", "upsample_flat.2.1.bias", "upsample_flat.4.0.weight", "upsample_flat.4.0.bias", "upsample_edge.2.1.weight", "upsample_edge.2.1.bias", "upsample_edge.4.0.weight", "upsample_edge.4.0.bias", "upsample_corner.2.1.weight", "upsample_corner.2.1.bias", "upsample_corner.4.0.weight", "upsample_corner.4.0.bias". 
	Unexpected key(s) in state_dict: "flat_map.2.0.weight", "flat_map.2.0.bias", "edge_map.2.0.weight", "edge_map.2.0.bias", "corner_map.2.0.weight", "corner_map.2.0.bias", "upsample_flat.2.0.weight", "upsample_flat.2.0.bias", "upsample_edge.2.0.weight", "upsample_edge.2.0.bias", "upsample_corner.2.0.weight", "upsample_corner.2.0.bias". 
	size mismatch for flat_map.3.0.weight: copying a param with shape torch.Size([3, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for flat_map.3.0.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for edge_map.3.0.weight: copying a param with shape torch.Size([3, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for edge_map.3.0.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for corner_map.3.0.weight: copying a param with shape torch.Size([3, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for corner_map.3.0.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for upsample_flat.3.0.weight: copying a param with shape torch.Size([3, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for upsample_flat.3.0.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for upsample_edge.3.0.weight: copying a param with shape torch.Size([3, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for upsample_edge.3.0.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for upsample_corner.3.0.weight: copying a param with shape torch.Size([3, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
	size mismatch for upsample_corner.3.0.bias: copying a param with shape torch.Size([3]) from checkpoint, the shape in current model is torch.Size([64]).
